- name: Python Bağımlılıklarını Kur
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright

      - name: Playwright Tarayıcılarını ve Sistem Bağımlılıklarını Kur
        run: |
          python -m playwright install chromium --with-deps

      - name: Botu Çalıştır
        run: |
          python generator.py
